"use strict";
exports.MOVIES = [
    { id: 1, name: 'Bad Moms',
        picture: 'images/bad-moms.jpg',
        summary: "Amy (Mila Kunis) has a great husband, overachieving children, beautiful home and successful career. Unfortunately, she's also overworked, exhausted and ready to snap. Fed up, she joins forces with two other stressed-out mothers (Kristen Bell, Kathryn Hahn) to get away from daily life and conventional responsibilities. As the gals go wild with their newfound freedom, they set themselves up for the ultimate showdown with PTA queen bee Gwendolyn and her clique of seemingly perfect moms.",
        review: "I am an avid film goer, I like mindless comedies...... Rarely have I watched a 'comedy' movie and not laughed through it's entirety.... Congratulations Bad Mom's you have made one of my rarer lists! It is a horrible example to set for anyone young actual mothers. It is unfunny to the point of being over the top trying too hard! The entire party scene has been done and beaten to death! The whole penis thing was unfunny and borderline sexist in it's own right. Some of the actresses have done very well in other parts, but here they all just sort of fall flat. It's a shameful movie and one I hope they are ashamed to have their names attached to.",
        trailer: "https://www.youtube.com/embed/iKCw-kqo3cs",
        director: "Jon Lucas, Scott Moore",
        cast: " Mila Kunis, Kathryn Hahn, Kristen Bell"
    },
    { id: 2, name: 'Boo a Madea Halloween',
        picture: 'images/boo-a-madea-halloween.jpg',
        summary: 'Madea winds up in the middle of mayhem when she spends a haunted Halloween fending off killers, paranormal poltergeists, ghosts, ghouls and zombies while keeping a watchful eye on a group of misbehaving teens.',
        review: "I love Tyler Perry's staple senior characters, Madea most of all of course! In the scenes where the 'grownups' are allowed to shine, it's pure gold. The best scene is their intro, Madea and the ever-high Aunt Bam are sitting on the front porch for trick-or-treater's and offering up more tricks than treats to the 'babies' that visit their door. Equally hilarious is the living room scene in which the elderly foursome has just arrived at Brian's house. The dialogue and comedic timing are great! In the scenes where the under 30 crowd take the spotlight, things fall flat. The teens and 20-somethings let the ball drop and entire scenes fail to deliver a chuckle despite fervent effort on the writer and editors part. It's either a shortcoming with casting or directing, or both.",
        trailer: "https://www.youtube.com/embed/G9-VHtJvPNs",
        director: "Tyler Perry",
        cast: "Tyler Perry, Cassi Davis, Patrice Lovely"
    },
    { id: 3, name: 'Doctor Strange',
        picture: 'images/doctor-strange.jpg',
        summary: 'A former neurosurgeon embarks on a journey of healing only to be drawn into the world of the mystic arts.',
        review: "Without giving away too much, Benedict Cumberbatch just kills it. He is one class actor. Cumberbatch rocks as Strange and pulls it off with ease. The impressions his portrayal gives us is that he was born to play the role of the ex-neurosurgeon turned Sorcerer Supreme. Such is the talent of the lead cast, that it represents just how good the movie was overall. Every normal movie watcher will love the action, humour, adventure and fantasy throughout the film.A solid new character introduced to the Marvel Cinematic Universe with loads of potential. Cumberbatch solidifies and anchors his role in the MCU as Stephen Strange in a similar fashion to RDJ doing so with Tony Stark.A must watch! Enjoy!",
        trailer: "https://www.youtube.com/embed/HSzx-zryEgM",
        director: "Scott Derrickson",
        cast: "Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams"
    },
    { id: 4, name: 'Finding Dory',
        picture: 'images/finding-dory.jpeg',
        summary: 'The friendly but forgetful blue tang fish begins a search for her long-lost parents, and everyone learns a few things about the real meaning of family along the way.',
        review: "i used to be a be pixar fan, and loved classic films like Nemo and Monster. However, since Steve Jobs sold Pixar to Disney, the creativity and imagination have died with the trade. Dory is no exception, feels like a recycled Nemo but with much worse plot, worse cgi, worse pretty much everything. It is pretty hard to believe, 15 years since the original Nemo, the quality of the animation actually has become worse.The only bright spot of the movie, was the 5 minute mini movie Piper. I should pixar makes a feature length movie for that.Wall-E was the last good pixar films. all junks after that. I wish jobs has never sold pixar to Disney.I wonder what junk will pixar dish out next year... sigh...",
        trailer: "https://www.youtube.com/embed/MKJA-VLpiCo",
        director: "Andrew Stanton, Angus MacLane",
        cast: "Ellen DeGeneres, Albert Brooks, Ed O'Neill"
    },
    { id: 5, name: 'Kevin Hart What Now',
        picture: 'images/kevin-hart-what-now.jpg',
        summary: "Comedian Kevin Hart performs in front of a crowd of 50,000 people at Philadelphia's outdoor venue, Lincoln Financial Field.",
        review: "This stand up special is not very good. I think it probably is just as simple as Kevin Hart having done too much stuff too quickly and too recently. I have liked his stuff in the past including his stand up comedy appearances and also his early movie roles. But his more recent stuff including starring movie roles in lesser quality movies and especially his stand up comedy are just not up to the same quality I'm used to seeing from him.I hope he takes some time off to write and develop some stronger stuff instead of just churning stuff out this quickly in the future, to bring the quality up.",
        trailer: "https://www.youtube.com/embed/iUfsjUgod3I",
        director: "Leslie Small, Tim Story",
        cast: "Kevin Hart, Don Cheadle, Halle Berry"
    },
    { id: 6, name: 'Inferno',
        picture: 'images/inferno-2016.jpg',
        summary: 'When Robert Langdon wakes up in an Italian hospital with amnesia, he teams up with Dr. Sienna Brooks, and together they must race across Europe against the clock to foil a deadly global plot.',
        review: "Dan Brown is one of my favorite writers, maybe Inferno was not his best book but it was still good enough. i've read it in 2 days , i know a lot of people that loved it. One of the best things about Inferno was the ending, and they decided to leave it out of the movie script...That was a big mistake, that's why i recommend everybody to give the book a chance even if u tried the movie...I gave the book 9 stars out of 10. I can only give the movie 4 stars out of 10. I'm sorry they changed the soul of the movie , they tried to make it more Hollywood and they made a big mistake...Thanks",
        trailer: "https://www.youtube.com/embed/RH2BD49sEZI",
        director: "Ron Howard",
        cast: "Tom Hanks, Felicity Jones, Irrfan Khan "
    },
    { id: 7, name: 'Miss Peregrines Home for Peculiar Children',
        picture: 'images/miss-peregrines-home-for-peculiar-children-.jpg',
        summary: "When Jacob discovers clues to a mystery that stretches across time, he finds Miss Peregrine's Home for Peculiar Children. But the danger deepens after he gets to know the residents and learns about their special powers.",
        review: "I went to the cinema yesterday to watch this movie. I had low expectations because Tim Burton's latest movies were boring but he finally made a decent, interesting movie that did not bore me at all!! Eva Green is amazing and thank God Johnny Depp and Helen Bonham Carter were not in this one AGAIN!! The script, the performances, the direction, the special effects all were decent and enjoyable! Don't get me wrong, it is a fantasy movie, don't expect to watch a masterpiece BUT I really liked it. Go with your kids (not very young, i'd say from 10 years of age and older) and your friends, you will relax and watch something interesting. Especially young people will find this movie really good! Don't hesitate to go to your nearest cinema and watch it! You won't be disappointed!",
        trailer: "https://www.youtube.com/embed/tV_IhWE4LP0",
        director: "Tim Burton",
        cast: "Eva Green, Asa Butterfield, Samuel L. Jackson"
    },
    { id: 8, name: 'Sausage Party',
        picture: 'images/sausage-party-.jpg',
        summary: 'A sausage strives to discover the truth about his existence.',
        review: "Saw the preview for this movie and had to see it. Saw it on opening weekend and the movie was more over the top than what I was expecting. The humor was dumbed down, from sex jokes to religion/race jokes, and finally about drugs. The end result was the most that I've laughed in a movie theatre in well over a decade, and the majority of the full theatre was also laughing hysterically. This movie will get a lot of complaints from prior who will want something deeper and meaningful, out the whole animation fiasco that's going on. At the end of it all this movie gets a 9 from myself as it is a solid and entertaining movie in my book.",
        trailer: "https://www.youtube.com/embed/MBdeE7mzED4",
        director: "Greg Tiernan, Conrad Vernon",
        cast: "Seth Rogen, Kristen Wiig, Jonah Hill"
    },
    { id: 9, name: 'Storks',
        picture: 'images/storks.jpg',
        summary: 'Storks have moved on from delivering babies to packages. But when an order for a baby appears, the best delivery stork must scramble to fix the error by delivering the baby.',
        review: "I admit that while it's not one of my favorite animated movies of the year, it's still definitely something I would recommend. I admit that it does start a bit slow. It really gets better when the character Tulip is introduced. She is the heart of this movie and by far the most entertaining part. Thank you for featuring her so much. Almost everything she says is funny. I guess I just have a soft spot for genki girls. Pinkie Pie is the one who comes to mind most at any time. She even has red (pink?) hair like her. The best parts are probably her interacting with her personas. I admit that the story makes little sense. How exactly are babies brought into this world now? We briefly get to see the process of how a baby is made. I love how big and epic this movie gets. Yes, it's technically short, but it still gives you everything you would want in a good movie. They have a lot of great details and it leads up to an exciting climax. As a huge fan of 'The Lego Movie', you have to watch the great short that precedes this. If only 'Looney Tunes' did stuff like that nowadays. It's great to see a good movie based on an original concept too. ",
        trailer: "https://www.youtube.com/embed/ZENmkJk9fBM",
        director: "Nicholas Stoller, Doug Sweetland",
        cast: "Andy Samberg, Katie Crown, Kelsey Grammer"
    },
    { id: 10, name: 'Suicide Squad',
        picture: 'images/suicide-squad-.jpg',
        summary: 'A secret government agency recruits some of the most dangerous incarcerated super-villains to form a defensive task force. Their first mission: save the world from the apocalypse.',
        review: "I am really really disappointed to be honest. I was waiting for this movie for so long, I loved Suicide Squad in Assault on Arkham and I was so happy when the news arrived about the live action movie. And as a massive Jared Leto fan I was extremely happy they chose him for the role of my all time favorite character, Joker. So I was hyped to see him, but the whole gang too. And what I got from the movie was equal with pure sadness. I mean, Jared was in it for a total 10 minutes and his role could have been easily left out, I only knew the characters because I read the comics and watched the wonderful animation (which by the way a 100 times better), the story telling was HORRIBLE, the actors could have been wonderful but they kinda lost in the terrible script. Will Smith, Margot Robbie and Viola Davis were fantastic but we didn't really get to know them... and the other characters were only there for... who know why? WHY DC, WHY? This story had so much promise and you ruined it... You should have adopted the Assault on Arkham into a live action movie... All these characters would needed a stand alone movie, and once we've got to know them then put them together... sure it would take years to build up a universe like that, but come on, that's what Marvel did and their movies are amazing! I am so, so sad right now... All of the actors deserve way better than this and they all have great potential",
        trailer: "https://www.youtube.com/embed/CmRih_VtVAs",
        director: "David Ayer",
        cast: "Will Smith, Jared Leto, Margot Robbie "
    },
    { id: 11, name: 'The Accountant',
        picture: 'images/the-accountant.jpg',
        summary: 'As a math savant uncooks the books for a new client, the Treasury Department closes in on his activities and the body count starts to rise.',
        review: "Yesterday I went to watch the Accountant movie. After watch the movie I felt a strong relation with another movie, Warrior (another movie that I really enjoyed). When I came back to my house, with a small research I saw that the director of both movies was the same, Gavin O'Connor. Now, I feel that I watched 2 movies with different histories but with the same essence. I really enjoyed this movie. It worth every penny. Ben Affleck did very well on this movie. Other actors too. Well done production. The action scenes were really well done and the Barrett .50 sound is amazing. I love that weapon.",
        trailer: "https://www.youtube.com/embed/DBfsgcswlYQ",
        director: "Gavin O'Connor",
        cast: "Ben Affleck, Anna Kendrick, J.K. Simmons "
    },
    { id: 12, name: 'The BFG',
        picture: 'images/the-bfg-2016.jpg',
        summary: 'A girl named Sophie encounters the Big Friendly Giant who, despite his intimidating appearance, turns out to be a kind-hearted soul who is considered an outcast by the other giants because, unlike them, he refuses to eat children.',
        review: "I read the BFG when I was a kid. Loved it. I watched the BFG when I was an adult. Didn't love it. Difference? I found that the whole movie lacked charm. It was 2 hours of 'this happened, then that happened. Now look at this special effect sequence. Now we're going to have people talk to each other', with no real establishment if of why I should care about anything going on or the characters themselves. As I said, the movie lacked engagement and charm. Sure, it was a Spielberg movie so the movie was not *technically* bad. The man knows how to put together a movie. However, this was not an engaging one. Some of the pacing was totally off in this film. Some jokes and sequences lasted WAY too long, where other important elements were pushed through too fast. At the end of the day, one might say 'well it's for kids'. To that, I say that the kids who were in the theatre seemed less than thrilled as well.'",
        trailer: "https://www.youtube.com/embed/GZ0Bey4YUGI",
        director: "Steven Spielberg",
        cast: "Mark Rylance, Ruby Barnhill, Penelope Wilton "
    },
    { id: 13, name: 'The Birth of A Nation',
        picture: 'images/the-birth-of-a-nation.jpg',
        summary: 'Nat Turner, a literate slave and preacher in the antebellum South, orchestrates an uprising.',
        review: "The Birth of a Nation was one of my most anticipated movies of this year. It won the Grand Jury prize in Sundance, and it tells the story of the failed slave rebellion led by Nat Turner. Everything about this movie that could have been interesting was instead constrained to convention. The score, which was fantastically simple yet powerful in the trailers leading up to the film was instead boring, and it overpowered many of the film's scenes. It came off as very clichéd when it instead could have been excellent. The characters in this movie were bland and uninteresting. In fact, I didn't care about a single one of them, which is a huge insult to a movie about slaves and the struggles they went through. The movie took a character as interesting and complex as Nat Turner, a man who was probably both insane and inspiring, and turned him into an everyday, bland man who just got a little too upset. The lead up to the movies climactic rebellion was decent. Nothing too interesting happened but, like the rest of the film, there wasn't too much to hate about it, The rebellion itself was also uninteresting and generic. Again the score was too loud and bombastic, and again Nate Parker's direction for these scenes showed his inexperience and his fear to break any convention and boundaries. Overall I was extremely disappointed by this film (more than maybe any other film this year) and I would say its one of the most average films of the year. Instead go watch the short film 'Possession' for a better depiction of Nat and 'Gangs of New York' if you want to see what this film's action scenes should have been like.",
        trailer: "https://www.youtube.com/embed/i18z1EQCoyg",
        director: "Nate Parker",
        cast: "Nate Parker, Armie Hammer, Penelope Ann Miller "
    },
    { id: 14, name: 'The Girl on the Train',
        picture: 'images/the-girl-on-the-train.jpg',
        summary: 'A divorcee becomes entangled in a missing persons investigation that promises to send shockwaves throughout her life.',
        review: "First off, I will admit that I've not read the bestselling book that The Girl on the Train is based on so my thoughts are based purely on the movie adaptation. I usually love a fast paced thriller with twists and turns to keep me metaphorically on the edge of cinema seat. The trailers had led me to believe this might be the case for The Girl on the Train. How wrong I was. The screenplay and direction were often sloppy while the editing was so messy it often felt like scenes were pieced together purely at random. I really struggled to warm to or identify with any of the characters in a film where all men are portrayed as controlling and deplorable and any sense of female empowerment is lost amidst the absurdity of the relentlessly twisting plot. I have to call out Emily Blunt's stunning lead performance - she steals every scene she's in with a nuanced, conflicted and honest portrayal of a complex and intriguing character. Quality support performances from Luke Evans and Haley Bennet help but don't save the movie and most other characters are so slight and one-dimensional that they fade into the background. The Girl on the Train felt like Gone Girl without the tension, emotion or drama.",
        trailer: "https://www.youtube.com/embed/KkoEE1i0CX8",
        director: "Tate Taylor",
        cast: "Emily Blunt, Haley Bennett, Rebecca Ferguson"
    },
    { id: 15, name: 'The Comedians Guide to Survival',
        picture: 'images/the-comedians-guide-to-survival-.jpg',
        summary: "One man's journey around the world to discover the secret of comedy.",
        review: "Puerile, inept and almost fascinatingly unfunny, this regrettable low-budget effort completely squanders a fertile premise and some big-name guest appearances.",
        trailer: "https://www.youtube.com/embed/9Tgj_pwDnB8",
        director: "Mark Murphy",
        cast: "Mohammed Ali, Jeannette Belaouane, Vas Blackwood"
    },
];
//# sourceMappingURL=movie-list.js.map